export default [
  { ticker: "BHP", name: "BHP Group Limited" },
  { ticker: "CBA", name: "Commonwealth Bank Of Australia." },
  { ticker: "CSL", name: "CSL Limited" },
  { ticker: "NAB", name: "National Australia Bank Limited" },
  { ticker: "WBC", name: "Westpac Banking Corporation" },
  { ticker: "ANZ", name: "ANZ Group Holdings Limited" },
  { ticker: "FMG", name: "Fortescue Ltd" },
  { ticker: "WES", name: "Wesfarmers Limited" },
  { ticker: "NEM", name: "Newmont Corporation" },
  { ticker: "MQG", name: "Macquarie Group Limited" },
  { ticker: "GMG", name: "Goodman Group" },
  { ticker: "SQ2", name: "Block Inc." },
  { ticker: "WDS", name: "Woodside Energy Group Ltd" },
  { ticker: "RIO", name: "Rio Tinto Limited" },
  { ticker: "RMD", name: "Resmed Inc" },
  { ticker: "TLS", name: "Telstra Group Limited" },
  { ticker: "TCL", name: "Transurban Group" },
  { ticker: "WOW", name: "Woolworths Group Limited" },
  { ticker: "WTC", name: "Wisetech Global Limited" },
  { ticker: "QBE", name: "QBE Insurance Group Limited" },
  { ticker: "ALL", name: "Aristocrat Leisure Limited" },
  { ticker: "STO", name: "Santos Limited" },
  { ticker: "REA", name: "REA Group Ltd" },
  { ticker: "JHX", name: "James Hardie Industries Plc" },
  { ticker: "AMC", name: "Amcor Plc" },
  { ticker: "NWS", name: "News Corporation.." },
  { ticker: "COL", name: "Coles Group Limited." },
  { ticker: "COH", name: "Cochlear Limited" },
  { ticker: "SUN", name: "Suncorp Group Limited" },
  { ticker: "BXB", name: "Brambles Limited" },
  { ticker: "XRO", name: "Xero Limited" },
  { ticker: "URW", name: "Unibail-Rodamco-Westfield" },
  { ticker: "REH", name: "Reece Limited" },
  { ticker: "ORG", name: "Origin Energy Limited" },
  { ticker: "NST", name: "Northern Star Resources Ltd" },
  { ticker: "SCG", name: "Scentre Group" },
  { ticker: "S32", name: "South32 Limited" },
  { ticker: "CPU", name: "Computershare Limited." },
  { ticker: "IAG", name: "Insurance Australia Group Limited" },
  { ticker: "FPH", name: "Fisher & Paykel Healthcare Corporation Limited" },
  { ticker: "MIN", name: "Mineral Resources Limited" },
  { ticker: "SVW", name: "Seven Group Holdings Limited" },
  { ticker: "MEZ", name: "Meridian Energy Limited" },
  { ticker: "CAR", name: "Car Group Limited" },
  { ticker: "LNW", name: "Light & Wonder Inc." },
  { ticker: "SHL", name: "Sonic Healthcare Limited" },
  { ticker: "PLS", name: "Pilbara Minerals Limited" },
  { ticker: "ASX", name: "ASX Limited" },
  { ticker: "RHC", name: "Ramsay Health Care Limited" },
  { ticker: "PME", name: "Pro Medicus Limited" },
  { ticker: "SOL", name: "Washington H Soul Pattinson & Company Limited" },
  { ticker: "TLC", name: "The Lottery Corporation Limited" },
  { ticker: "APA", name: "APA Group" },
  { ticker: "SGP", name: "Stockland" },
  { ticker: "AIA", name: "Auckland International Airport Limited" },
  { ticker: "BSL", name: "Bluescope Steel Limited" },
  { ticker: "NXT", name: "Nextdc Limited" },
  { ticker: "QAN", name: "Qantas Airways Limited" },
  { ticker: "MPL", name: "Medibank Private Limited" },
  { ticker: "EDV", name: "Endeavour Group Limited" },
  { ticker: "TWE", name: "Treasury Wine Estates Limited" },
  { ticker: "AFI", name: "Australian Foundation Investment Company Limited" },
  { ticker: "ORI", name: "Orica Limited" },
  { ticker: "VCX", name: "Vicinity Centres" },
  { ticker: "ALU", name: "Altium Limited" },
  { ticker: "SEK", name: "Seek Limited" },
  { ticker: "ALD", name: "Ampol Limited" },
  { ticker: "TPG", name: "TPG Telecom Limited." },
  { ticker: "CSC", name: "Capstone Copper Corp." },
  { ticker: "MGR", name: "Mirvac Group" },
  { ticker: "WOR", name: "Worley Limited" },
  { ticker: "IFT", name: "Infratil Limited." },
  { ticker: "GPT", name: "Gpt Group" },
  { ticker: "MCY", name: "Mercury Nz Limited" },
  { ticker: "ALX", name: "Atlas Arteria" },
  { ticker: "DXS", name: "Dexus" },
  { ticker: "LTM", name: "Arcadium Lithium Plc" },
  { ticker: "YAL", name: "Yancoal Australia Limited" },
  { ticker: "EVN", name: "Evolution Mining Limited" },
  { ticker: "SPK", name: "Spark New Zealand Limited" },
  { ticker: "GQG", name: "Gqg Partners Inc." },
  { ticker: "AZJ", name: "Aurizon Holdings Limited" },
  { ticker: "NXG", name: "Nexgen Energy (Canada) Ltd" },
  { ticker: "WHC", name: "Whitehaven Coal Limited" },
  { ticker: "ARG", name: "Argo Investments Limited" },
  { ticker: "JBH", name: "Jb Hi-Fi Limited" },
  { ticker: "ALQ", name: "ALS Limited" },
  { ticker: "SDF", name: "Steadfast Group Limited" },
  { ticker: "AGL", name: "AGL Energy Limited." },
  { ticker: "CEN", name: "Contact Energy Limited" },
  { ticker: "BLD", name: "Boral Limited." },
  { ticker: "QUB", name: "Qube Holdings Limited" },
  { ticker: "EBO", name: "Ebos Group Limited" },
  { ticker: "LYC", name: "Lynas Rare Earths Limited" },
  { ticker: "CWY", name: "Cleanaway Waste Management Limited" },
  { ticker: "IGO", name: "IGO Limited" },
  { ticker: "CHC", name: "Charter Hall Group" },
  { ticker: "BEN", name: "Bendigo And Adelaide Bank Limited" },
  { ticker: "HVN", name: "Harvey Norman Holdings Limited" },
  { ticker: "VEA", name: "Viva Energy Group Limited" },
  { ticker: "IPL", name: "Incitec Pivot Limited" },
  { ticker: "ATM", name: "Aneka Tambang (Persero) Tbk (Pt)" },
  { ticker: "VUK", name: "Virgin Money Uk Plc" },
  { ticker: "TNE", name: "Technology One Limited" },
  { ticker: "TLX", name: "Telix Pharmaceuticals Limited" },
  { ticker: "NWL", name: "Netwealth Group Limited" },
  { ticker: "PMV", name: "Premier Investments Limited" },
  { ticker: "PDN", name: "Paladin Energy Ltd" },
  { ticker: "AWC", name: "Alumina Limited" },
  { ticker: "IEL", name: "IDP Education Limited" },
  { ticker: "FLT", name: "Flight Centre Travel Group Limited" },
  { ticker: "SFR", name: "Sandfire Resources Limited" },
  { ticker: "A2M", name: "The A2 Milk Company Limited" },
  { ticker: "LLC", name: "Lendlease Group" },
  { ticker: "CGF", name: "Challenger Limited" },
  { ticker: "CSR", name: "CSR Limited" },
  { ticker: "NIC", name: "Nickel Industries Limited" },
  { ticker: "MTS", name: "Metcash Limited" },
  { ticker: "BKW", name: "Brickworks Limited" },
  { ticker: "NHC", name: "New Hope Corporation Limited" },
  { ticker: "RWC", name: "Reliance Worldwide Corporation Limited" },
  { ticker: "BOQ", name: "Bank Of Queensland Limited." },
  { ticker: "BRG", name: "Breville Group Limited" },
  { ticker: "CIA", name: "Champion Iron Limited" },
  { ticker: "BPT", name: "Beach Energy Limited" },
  { ticker: "NHF", name: "Nib Holdings Limited" },
  { ticker: "DMP", name: "Domino'S Pizza Enterprises Limited" },
  { ticker: "ANN", name: "Ansell Limited" },
  { ticker: "LOV", name: "Lovisa Holdings Limited" },
  { ticker: "HUB", name: "Hub24 Limited" },
  { ticker: "ILU", name: "Iluka Resources Limited" },
  { ticker: "WEB", name: "Webjet Limited" },
  { ticker: "MGF", name: "Magellan Global Fund." },
  { ticker: "APE", name: "Eagers Automotive Limited" },
  { ticker: "ARB", name: "Arb Corporation Limited." },
  { ticker: "VNT", name: "Ventia Services Group Limited" },
  { ticker: "SUL", name: "Super Retail Group Limited" },
  { ticker: "AUB", name: "AUB Group Limited" },
  { ticker: "360", name: "Life360 Inc." },
  { ticker: "DOW", name: "Downer Edi Limited" },
  { ticker: "PRU", name: "Perseus Mining Limited" },
  { ticker: "SMR", name: "Stanmore Resources Limited" },
  { ticker: "LTR", name: "Liontown Resources Limited" },
  { ticker: "NSR", name: "National Storage Reit" },
  { ticker: "AMP", name: "AMP Limited" },
  { ticker: "ORA", name: "Orora Limited" },
  { ticker: "CNU", name: "Chorus Limited" },
  { ticker: "BFL", name: "BSP Financial Group Limited" },
  { ticker: "PPT", name: "Perpetual Limited" },
  { ticker: "FBU", name: "Fletcher Building Limited" },
  { ticker: "NEU", name: "Neuren Pharmaceuticals Limited" },
  { ticker: "DRR", name: "Deterra Royalties Limited" },
  { ticker: "BWP", name: "BWP Trust" },
  { ticker: "RGN", name: "Region Group" },
  { ticker: "HDN", name: "Homeco Daily Needs Reit" },
  { ticker: "CLW", name: "Charter Hall Long Wale Reit" },
  { ticker: "PXA", name: "Pexa Group Limited" },
  { ticker: "PNI", name: "Pinnacle Investment Management Group Limited" },
  { ticker: "NEC", name: "Nine Entertainment Co. Holdings Limited" },
  { ticker: "SNZ", name: "Summerset Group Holdings Limited" },
  { ticker: "DEG", name: "De Grey Mining Limited" },
  { ticker: "GNE", name: "Genesis Energy Limited" },
  { ticker: "SGM", name: "Sims Limited" },
  { ticker: "HMC", name: "HMC Capital Limited" },
  { ticker: "RMS", name: "Ramelius Resources Limited" },
  { ticker: "MP1", name: "Megaport Limited" },
  { ticker: "BOE", name: "Boss Energy Ltd" },
  { ticker: "EMR", name: "Emerald Resources Nl" },
  { ticker: "MXT", name: "Metrics Master Income Trust" },
  { ticker: "CTD", name: "Corporate Travel Management Limited" },
  { ticker: "MAQ", name: "Macquarie Technology Group Limited" },
  { ticker: "SIG", name: "Sigma Healthcare Limited" },
  { ticker: "ABC", name: "Adbri Limited" },
  { ticker: "CIP", name: "Centuria Industrial Reit" },
  { ticker: "MFF", name: "Mff Capital Investments Limited" },
  { ticker: "CRN", name: "Coronado Global Resources Inc." },
  { ticker: "PSI", name: "Psc Insurance Group Limited" },
  { ticker: "NUF", name: "Nufarm Limited" },
  { ticker: "BGL", name: "Bellevue Gold Limited" },
  { ticker: "DHG", name: "Domain Holdings Australia Limited." },
  { ticker: "CQR", name: "Charter Hall Retail Reit" },
  { ticker: "EVT", name: "Evt Limited" },
  { ticker: "GMD", name: "Genesis Minerals Limited" },
  { ticker: "CDA", name: "Codan Limited" },
  { ticker: "DDR", name: "Dicker Data Limited" },
  { ticker: "INA", name: "Ingenia Communities Group" },
  { ticker: "TUA", name: "Tuas Limited" },
  { ticker: "LSF", name: "L1 Long Short Fund Limited" },
  { ticker: "GNC", name: "Graincorp Limited" },
  { ticker: "WLE", name: "Wam Leaders Limited" },
  { ticker: "ZIM", name: "Zimplats Holdings Limited" },
  { ticker: "CMM", name: "Capricorn Metals Ltd" },
  { ticker: "GOZ", name: "Growthpoint Properties Australia" },
  { ticker: "RDX", name: "Redox Limited" },
  { ticker: "GOR", name: "Gold Road Resources Limited" },
  { ticker: "WAM", name: "Wam Capital Limited" },
  { ticker: "SSR", name: "SSR Mining Inc." },
  { ticker: "JLG", name: "Johns Lyng Group Limited" },
  { ticker: "AIZ", name: "Air New Zealand Limited" },
  { ticker: "TAH", name: "Tabcorp Holdings Limited" },
  { ticker: "WPR", name: "Waypoint Reit" },
  { ticker: "IRE", name: "Iress Limited" },
  { ticker: "MFG", name: "Magellan Financial Group Limited" },
  { ticker: "BAP", name: "Bapcor Limited" },
  { ticker: "RRL", name: "Regis Resources Limited" },
  { ticker: "DYL", name: "Deep Yellow Limited" },
  { ticker: "IFL", name: "Insignia Financial Ltd" },
  { ticker: "JDO", name: "Judo Capital Holdings Limited" },
  { ticker: "SDR", name: "Siteminder Limited" },
  { ticker: "KLS", name: "Kelsian Group Limited" },
  { ticker: "AD8", name: "Audinate Group Limited" },
  { ticker: "KAR", name: "Karoon Energy Ltd" },
  { ticker: "LIC", name: "Lifestyle Communities Limited" },
  { ticker: "ASK", name: "Abacus Storage King" },
  { ticker: "IPH", name: "Iph Limited" },
  { ticker: "RED", name: "Red 5 Limited" },
  { ticker: "ZIP", name: "Zip Co Limited.." },
  { ticker: "MGH", name: "Maas Group Holdings Limited" },
  { ticker: "TPW", name: "Temple & Webster Group Ltd" },
  { ticker: "PNV", name: "Polynovo Limited" },
  { ticker: "SLX", name: "Silex Systems Limited" },
  { ticker: "GUD", name: "G.U.D. Holdings Limited" },
  { ticker: "ING", name: "Inghams Group Limited" },
  { ticker: "CNI", name: "Centuria Capital Group" },
  { ticker: "DBI", name: "Dalrymple Bay Infrastructure Limited" },
  { ticker: "WAF", name: "West African Resources Limited" },
  { ticker: "ADT", name: "Adriatic Metals Plc" },
  { ticker: "MAD", name: "Mader Group Limited" },
  { ticker: "MAC", name: "Metals Acquisition Limited" },
  { ticker: "BKI", name: "Bki Investment Company Limited" },
  { ticker: "BGA", name: "Bega Cheese Limited" },
  { ticker: "SLR", name: "Silver Lake Resources Limited" },
  { ticker: "ARF", name: "Arena Reit." },
  { ticker: "MSB", name: "Mesoblast Limited" },
  { ticker: "FRW", name: "Freightways Group Limited" },
  { ticker: "ELD", name: "Elders Limited" },
  { ticker: "MMS", name: "Mcmillan Shakespeare Limited" },
  { ticker: "MND", name: "Monadelphous Group Limited" },
  { ticker: "AUI", name: "Australian United Investment Company Limited" },
  { ticker: "NCK", name: "Nick Scali Limited" },
  { ticker: "SGR", name: "The Star Entertainment Group Limited" },
  { ticker: "NWH", name: "Nrw Holdings Limited" },
  { ticker: "LFG", name: "Liberty Financial Group" },
  { ticker: "LFS", name: "Latitude Group Holdings Limited" },
  { ticker: "PWH", name: "Pwr Holdings Limited" },
  { ticker: "ERA", name: "Energy Resources Of Australia Limited" },
  { ticker: "REG", name: "Regis Healthcare Limited" },
  { ticker: "OCL", name: "Objective Corporation Limited" },
  { ticker: "DTL", name: "Data#3 Limited" },
  { ticker: "CU6", name: "Clarity Pharmaceuticals Ltd" },
  { ticker: "SIQ", name: "Smartgroup Corporation Ltd" },
  { ticker: "SKC", name: "Skycity Entertainment Group Limited" },
  { ticker: "ABB", name: "Aussie Broadband Limited" },
  { ticker: "CTT", name: "Cettire Limited" },
  { ticker: "HLI", name: "Helia Group Limited" },
  { ticker: "WA1", name: "Wa1 Resources Ltd" },
  { ticker: "CKF", name: "Collins Foods Limited" },
  { ticker: "DUI", name: "Diversified United Investment Limited" },
  { ticker: "SGF", name: "Sg Fleet Group Limited" },
  { ticker: "IMD", name: "Imdex Limited" },
  { ticker: "CCP", name: "Credit Corp Group Limited" },
  { ticker: "CMW", name: "Cromwell Property Group" },
  { ticker: "ABG", name: "Abacus Group" },
  { ticker: "AX1", name: "Accent Group Limited" },
  { ticker: "APM", name: "Apm Human Services International Limited" },
  { ticker: "MRM", name: "Mma Offshore Limited" },
  { ticker: "WGX", name: "Westgold Resources Limited." },
  { ticker: "UOS", name: "United Overseas Australia Limited" },
  { ticker: "JIN", name: "Jumbo Interactive Limited" },
  { ticker: "GEM", name: "G8 Education Limited" },
  { ticker: "BGP", name: "Briscoe Group Australasia Limited" },
  { ticker: "HSN", name: "Hansen Technologies Limited" },
  { ticker: "A4N", name: "Alpha Hpa Limited" },
  { ticker: "VSL", name: "Vulcan Steel Limited" },
  { ticker: "DXI", name: "Dexus Industria Reit." },
  { ticker: "CQE", name: "Charter Hall Social Infrastructure Reit" },
  { ticker: "FPR", name: "Fleetpartners Group Limited" },
  { ticker: "PRN", name: "Perenti Limited" },
  { ticker: "ASB", name: "Austal Limited" },
  { ticker: "OML", name: "Ooh!Media Limited" },
  { ticker: "RSG", name: "Resolute Mining Limited" },
  { ticker: "HLS", name: "Healius Limited" },
  { ticker: "PL8", name: "Plato Income Maximiser Limited." },
  { ticker: "SNL", name: "Supply Network Limited" },
  { ticker: "NGI", name: "Navigator Global Investments Limited" },
  { ticker: "HGH", name: "Heartland Group Holdings Limited" },
  { ticker: "PGF", name: "Pm Capital Global Opportunities Fund Limited" },
  { ticker: "NAN", name: "Nanosonics Limited" },
  { ticker: "MAF", name: "Ma Financial Group Limited" },
  { ticker: "AAC", name: "Australian Agricultural Company Limited." },
  { ticker: "LOT", name: "Lotus Resources Limited" },
  { ticker: "EQT", name: "Eqt Holdings Limited" },
  { ticker: "CIN", name: "Carlton Investments Limited" },
  { ticker: "DJW", name: "Djerriwarrh Investments Limited" },
  { ticker: "RFF", name: "Rural Funds Group" },
  { ticker: "SSM", name: "Service Stream Limited" },
  { ticker: "GTK", name: "Gentrack Group Limited" },
  { ticker: "WGB", name: "Wam Global Limited" },
  { ticker: "CBO", name: "Cobram Estate Olives Limited" },
  { ticker: "TIE", name: "Tietto Minerals Limited" },
  { ticker: "PFP", name: "Propel Funeral Partners Limited" },
  { ticker: "CUV", name: "Clinuvel Pharmaceuticals Limited" },
  { ticker: "KKC", name: "Kkr Credit Income Fund" },
  { ticker: "RPL", name: "Regal Partners Limited" },
  { ticker: "WTN", name: "Winton Land Limited" },
  { ticker: "BRE", name: "Brazilian Rare Earths Limited" },
  { ticker: "NXL", name: "Nuix Limited" },
  { ticker: "QAL", name: "Qualitas Limited" },
  { ticker: "BMN", name: "Bannerman Energy Ltd" },
  { ticker: "COF", name: "Centuria Office Reit" },
  { ticker: "RIC", name: "Ridley Corporation Limited" },
  { ticker: "GWA", name: "Gwa Group Limited." },
  { ticker: "QRI", name: "Qualitas Real Estate Income Fund" },
  { ticker: "SLC", name: "Superloop Limited" },
  { ticker: "BCI", name: "Bci Minerals Limited" },
  { ticker: "PPM", name: "Pepper Money Limited" },
  { ticker: "LRS", name: "Latin Resources Limited" },
  { ticker: "HCW", name: "Healthco Healthcare And Wellness Reit" },
  { ticker: "NBI", name: "Nb Global Corporate Income Trust" },
  { ticker: "HPI", name: "Hotel Property Investments" },
  { ticker: "MOT", name: "Metrics Income Opportunities Trust" },
  { ticker: "C79", name: "Chrysos Corporation Limited" },
  { ticker: "IFM", name: "Infomedia Ltd" },
  { ticker: "GCI", name: "Gryphon Capital Income Trust" },
  { ticker: "BLX", name: "Beacon Lighting Group Limited" },
  { ticker: "SPR", name: "Spartan Resources Limited" },
  { ticker: "MIR", name: "Mirrabooka Investments Limited" },
  { ticker: "MYX", name: "Mayne Pharma Group Limited" },
  { ticker: "DRO", name: "Droneshield Limited" },
  { ticker: "STX", name: "Strike Energy Limited" },
  { ticker: "RF1", name: "Regal Investment Fund" },
  { ticker: "PTM", name: "Platinum Asset Management Limited" },
  { ticker: "WHF", name: "Whitefield Industrials Limited" },
  { ticker: "VUL", name: "Vulcan Energy Resources Limited" },
  { ticker: "MYR", name: "Myer Holdings Limited" },
  { ticker: "BVS", name: "Bravura Solutions Limited." },
  { ticker: "FCL", name: "Fineos Corporation Holdings Plc" },
  { ticker: "WC8", name: "Wildcat Resources Limited" },
  { ticker: "MVF", name: "Monash Ivf Group Limited" },
  { ticker: "DVP", name: "Develop Global Limited" },
  { ticker: "OBM", name: "Ora Banda Mining Ltd" },
  { ticker: "IDX", name: "Integral Diagnostics Limited" },
  { ticker: "PPC", name: "Peet Limited" },
  { ticker: "IMU", name: "Imugene Limited" },
  { ticker: "RUL", name: "Rpmglobal Holdings Limited" },
  { ticker: "WBT", name: "Weebit Nano Ltd" },
  { ticker: "IMM", name: "Immutep Limited" },
  { ticker: "OPH", name: "Ophir High Conviction Fund" },
  { ticker: "JMS", name: "Jupiter Mines Limited." },
  { ticker: "HM1", name: "Hearts And Minds Investments Limited" },
  { ticker: "COE", name: "Cooper Energy Limited" },
  { ticker: "VG1", name: "Vgi Partners Global Investments Limited" },
  { ticker: "MGX", name: "Mount Gibson Iron Limited" },
  { ticker: "PMT", name: "Patriot Battery Metals Inc." },
  { ticker: "MAH", name: "Macmahon Holdings Limited" },
  { ticker: "PAC", name: "Pacific Current Group Limited" },
  { ticker: "ASG", name: "Autosports Group Limited." },
  { ticker: "AEF", name: "Australian Ethical Investment Limited" },
  { ticker: "SST", name: "Steamships Trading Company Limited" },
  { ticker: "PYC", name: "Pyc Therapeutics Limited" },
  { ticker: "QOR", name: "Qoria Limited" },
  { ticker: "FGG", name: "Future Generation Global Limited" },
  { ticker: "AQZ", name: "Alliance Aviation Services Limited" },
  { ticker: "IPX", name: "Iperionx Limited" },
  { ticker: "BRN", name: "Brainchip Holdings Ltd" },
  { ticker: "ACL", name: "Australian Clinical Labs Limited" },
  { ticker: "LYL", name: "Lycopodium Limited" },
  { ticker: "GRR", name: "Grange Resources Limited." },
  { ticker: "FGX", name: "Future Generation Australia Limited" },
  { ticker: "TYR", name: "Tyro Payments Limited" },
  { ticker: "KGN", name: "Kogan.Com Ltd" },
];
